services:
  postgres:
    image: postgres:16-alpine
    container_name: todo-postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
      POSTGRES_USER: user
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d todolist" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg-initdb.d:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
