logging.level.sql=INFO
logging.level.web=INFO
logging.level.r2dbc=INFO
logging.level.org.eljabali.sami.todo=INFO
logging.file.name=app.log
spring.sql.init.mode=never
# do not expose info/env for the public
management.endpoints.web.exposure.include=openapi,swaggerui,health